library(ggplot2)
install.packages("car")
install.packages("pastecs")
install.packages("psych")
library(car)
library(psych)
library(pastecs)
burnoutData<-read.delim("C:/Users/kurti/OneDrive/Documents/R/Data files/Burnout.dat", header = TRUE)
by(data = burnoutData$research, INDICES = burnoutData$burnout, FUN = stat.desc, basic = FALSE, norm = TRUE)
burntData<-subset(burnoutData, burnoutData$burnout=="Burnt Out")
notburntD<-subset(burnoutData, burnoutData$burnout=="Not Burnt Out")
histburnt<-ggplot(burntData, aes(research)) + geom_histogram(aes(y = ..density..), fill = "white", colour = "black", binwidth = 4) + labs(x = "Stress Caused By Research", y = "Density") + stat_function(fun=dnorm, args=list(mean = mean(burntData$research, na.rm = TRUE), sd = sd(burntData$research, na.rm = TRUE)), colour = "red", size=1)
histnotBurnt<-ggplot(notburntD, aes(research)) + geom_histogram(aes(y = ..density..), fill = "white", colour = "black", binwidth = 4) + labs(x = "Stress Caused By Research", y = "Density") + stat_function(fun=dnorm, args=list(mean = mean(burntData$research, na.rm = TRUE), sd = sd(burntData$research, na.rm = TRUE)), colour = "red", size=1)
burntqq<-qplot(sample=burntData$research)
notBurntqq<-qplot(sample=notburntD$research)
by(burnoutData$research, burnoutData$burnout, shapiro.test)
leveneTest(burnoutData$research, burnoutData$burnout, center = mean)
