bigMacData<-read.csv("C:/Users/kurti/OneDrive/Documents/R/BigMacData.csv", header = TRUE)
stat.desc(bigMacData$time, basic = TRUE, norm = TRUE)
bigMbar<-ggplot(bigMacData, aes(weight, time))
bigMbar + stat_summary(fun.y = mean, geom = "bar", fill = "White", colour = "Black") + stat_summary(fun.data = mean_cl_normal, geom = "errorbar", position = position_dodge(width=0.90), width = 0.4) + labs(x = "Weight Type of Person", y = "Time in Seconds")
bigBoxplot<-ggplot(bigMacData, aes(weight, time))
bigBoxplot + geom_boxplot() + labs(x = "Weight Type of Person", y = "Time in Seconds")
nonFattyData<-subset(bigMacData, bigMacData$weight=="normal weight")
fattyData<-subset(bigMacData, bigMacData$weight=="overweight")
nonFattyHist<-ggplot(nonFattyData, aes(time)) + geom_histogram(aes(y = ..density..), colour = "black", fill = "white", binwidth = 35) + labs(x = "Time to Eat Mac Meal in Seconds", y = "Density") + stat_function(fun=dnorm, args=list(mean = mean(nonFattyData$time, na.rm = TRUE), sd = sd(nonFattyData$time, na.rm = TRUE)), colour = "red", size=1)
fattyHist<-ggplot(fattyData, aes(time)) + geom_histogram(aes(y = ..density..), colour = "black",  fill = "white", binwidth = 35) + labs(x = "Time to Eat Mac Meal in Seconds", y = "Density") + stat_function(fun=dnorm, args=list(mean = mean(fattyData$time, na.rm = TRUE), sd = sd(fattyData$time, na.rm = TRUE)), colour = "red", size=1)
qqNotF<-qplot(sample=nonFattyData$time)
qqFatt<-qplot(sample=fattyData$time)
by(bigMacData[, c("time")], bigMacData$weight, stat.desc, basic = FALSE, norm = TRUE)
by(bigMacData$time, bigMacData$weight, shapiro.test)
leveneTest(bigMacData$time, bigMacData$weight, center = mean)

TeachResData<-read.csv("C:/Users/kurti/OneDrive/Documents/R/TeachResearchData.csv", header = TRUE)
Teachscatter <- ggplot(TeachResData, aes(rating_1, num_pubs))
Teachscatter + geom_point() + geom_smooth(method = "lm", colour = "Blue") + labs(x="Average Quality Rating of Instructor", y = "Number of Published Articles") 
TeachResearchDataSet<-read.csv("C:/Users/kurti/OneDrive/Documents/R/TeachResearchDataSet.csv", header = TRUE)
line<-ggplot(TeachResearchDataSet, aes(class_pubs,  rating_1))
line + stat_summary(fun.y = mean, geom = "point") + stat_summary(fun.y = mean, geom = "line", aes(group = 1), colour = "Blue", linetype = "dashed") + stat_summary(fun.data = mean_cl_boot, geom = "errorbar", width = 0.2) + labs(x = "Publication Class", y = "Average Quality Rating of the Instructor")